//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTrasladista_consumeWCF.ServiceReference1 {
    using System;
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateTimeFormatFlags", Namespace="http://schemas.datacontract.org/2004/07/System.Globalization")]
    public enum DateTimeFormatFlags : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UseGenitiveMonth = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UseLeapYearMonth = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UseSpacesInMonthNames = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UseHebrewRule = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UseSpacesInDayNames = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UseDigitPrefixInTokens = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotInitialized = -1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenOperador", ReplyAction="http://tempuri.org/IService1/ObtenOperadorResponse")]
        WebTrasladista_consumeWCF.ServiceReference1.ObtenOperadorResponse ObtenOperador(WebTrasladista_consumeWCF.ServiceReference1.ObtenOperadorRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenOperador", ReplyAction="http://tempuri.org/IService1/ObtenOperadorResponse")]
        System.Threading.Tasks.Task<WebTrasladista_consumeWCF.ServiceReference1.ObtenOperadorResponse> ObtenOperadorAsync(WebTrasladista_consumeWCF.ServiceReference1.ObtenOperadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MuestraDatos", ReplyAction="http://tempuri.org/IService1/MuestraDatosResponse")]
        void MuestraDatos(System.Collections.Generic.List<string> cad, System.Web.UI.WebControls.DropDownList cmb1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MuestraDatos", ReplyAction="http://tempuri.org/IService1/MuestraDatosResponse")]
        System.Threading.Tasks.Task MuestraDatosAsync(System.Collections.Generic.List<string> cad, System.Web.UI.WebControls.DropDownList cmb1);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenOperador", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenOperadorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string msj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Collections.Generic.List<int> ids;
        
        public ObtenOperadorRequest() {
        }
        
        public ObtenOperadorRequest(string msj, System.Collections.Generic.List<int> ids) {
            this.msj = msj;
            this.ids = ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenOperadorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenOperadorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<string> ObtenOperadorResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string msj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Collections.Generic.List<int> ids;
        
        public ObtenOperadorResponse() {
        }
        
        public ObtenOperadorResponse(System.Collections.Generic.List<string> ObtenOperadorResult, string msj, System.Collections.Generic.List<int> ids) {
            this.ObtenOperadorResult = ObtenOperadorResult;
            this.msj = msj;
            this.ids = ids;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebTrasladista_consumeWCF.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebTrasladista_consumeWCF.ServiceReference1.IService1>, WebTrasladista_consumeWCF.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebTrasladista_consumeWCF.ServiceReference1.ObtenOperadorResponse WebTrasladista_consumeWCF.ServiceReference1.IService1.ObtenOperador(WebTrasladista_consumeWCF.ServiceReference1.ObtenOperadorRequest request) {
            return base.Channel.ObtenOperador(request);
        }
        
        public System.Collections.Generic.List<string> ObtenOperador(ref string msj, ref System.Collections.Generic.List<int> ids) {
            WebTrasladista_consumeWCF.ServiceReference1.ObtenOperadorRequest inValue = new WebTrasladista_consumeWCF.ServiceReference1.ObtenOperadorRequest();
            inValue.msj = msj;
            inValue.ids = ids;
            WebTrasladista_consumeWCF.ServiceReference1.ObtenOperadorResponse retVal = ((WebTrasladista_consumeWCF.ServiceReference1.IService1)(this)).ObtenOperador(inValue);
            msj = retVal.msj;
            ids = retVal.ids;
            return retVal.ObtenOperadorResult;
        }
        
        public System.Threading.Tasks.Task<WebTrasladista_consumeWCF.ServiceReference1.ObtenOperadorResponse> ObtenOperadorAsync(WebTrasladista_consumeWCF.ServiceReference1.ObtenOperadorRequest request) {
            return base.Channel.ObtenOperadorAsync(request);
        }
        
        public void MuestraDatos(System.Collections.Generic.List<string> cad, System.Web.UI.WebControls.DropDownList cmb1) {
            base.Channel.MuestraDatos(cad, cmb1);
        }
        
        public System.Threading.Tasks.Task MuestraDatosAsync(System.Collections.Generic.List<string> cad, System.Web.UI.WebControls.DropDownList cmb1) {
            return base.Channel.MuestraDatosAsync(cad, cmb1);
        }
    }
}
